ARG sourceimage=khulnasoft/tradescope
ARG sourcetag=develop
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-tradeai.txt /tradescope/

RUN pip install -r requirements-tradeai.txt --user --no-cache-dir
